#
# Configuration file for tracking using sliding
# 

dynamics:
    xLenght: 0.07 #  [meter]
    yLenght: 0.09 #  [meter]
    pusherRadious: 0.01 #  [meter]
    pusherFricCoef: 0.2
    pusherForceLim:  0.3
    pusherAngleVelLim: 2.0
    # Kz_max: 50
    # Kz_min: 0.1
    Kz_max: 0.
    Kz_min: 0.

TO:
    # contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    contactMode: 'sliding_mi'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    # solverName: 'knitro'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    solverName: 'gurobi'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    W_x: [1.0, 1.0, 0.01, 0.]  # diagonal state weights
    W_u: [0.01, 0.01, 0., 0.]  # diagonal control weights
    # W_u: [0.0, 0.0, 0.0, 0.]  # diagonal control weights
    K_goal: 10
    X_goal: null
    # X_goal: [0.3, 0.4, 0., 0.]
    # linDynFlag: False
    linDynFlag: True
    codeGenFlag: False
    noPrintingFlag: True
    phases: null
    numObs: 0
    # phases: [1, 5, 5, 5, 3]
